import Head from "next/head";
<<<<<<< HEAD
import { ThemeProvider } from "@mui/material";
import { appTheme } from "../themes/theme";
import styles from "../styles/Home.module.css";
import TodoTable from "../components/TodoTable";
import WelcomeHeader from "../components/WelcomeHeader";
import CssBaseline from "@mui/material/CssBaseline";
import { useUser } from "@auth0/nextjs-auth0/";
=======
import styles from "../styles/Home.module.css";
import AgendaBar from "../components/AgendaBar";
import ClassModules from "../components/ClassModules";
import WelcomeBar from "../components/WelcomeBar";
import { useUser } from "@auth0/nextjs-auth0/dist/frontend/use-user";
>>>>>>> 445f4f51def2c33b35426d0aa78c622a422f8981

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  if (!user) {
    return (
<<<<<<< HEAD
      <ThemeProvider theme={appTheme}>
        <main className={styles.main}>
          <WelcomeHeader />
          <a href="/api/auth/login">Login</a>
        </main>
      </ThemeProvider>
=======
      <div>
        <main className={styles.main}>
          <WelcomeBar />
          <a href="/api/auth/login">Login</a>
        </main>
      </div>
>>>>>>> 445f4f51def2c33b35426d0aa78c622a422f8981
    );
  }

  return (
    user && (
<<<<<<< HEAD
      <ThemeProvider theme={appTheme}>
        <CssBaseline>
          <div className={styles.container}>
            <Head>
              <title>Your Agenda</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
              <WelcomeHeader />
              <TodoTable />
              <a href="/api/auth/logout">Logout</a>
            </main>
          </div>
        </CssBaseline>
      </ThemeProvider>
=======
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <WelcomeBar />
          <a href="/api/auth/logout">Logout</a>

          <AgendaBar />

          <ClassModules />
        </main>
      </div>
>>>>>>> 445f4f51def2c33b35426d0aa78c622a422f8981
    )
  );
}
