import Head from "next/head";
import styles from "../styles/Home.module.css";
import ModuleTable from "../components/ModuleTable";
import WelcomeHeader from "../components/WelcomeHeader";
import NavBar from "../components/NavBar";
import { useUser } from "@auth0/nextjs-auth0/";
import { Button } from "@mui/material";
import Link from "next/link";

export default function Home() {
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  if (!user) {
    return (
      <main className={styles.main}>
        <WelcomeHeader />
        <a href="/api/auth/login">Login</a>
      </main>
    );
  }

  return (
    user && (
      <div className={styles.container}>
        <Head>
          <title>Your Agenda</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />
        <main className={styles.main}>
          <WelcomeHeader />
          <ModuleTable />
        </main>
      </div>
    )
  );
}
